### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by akevalion** [ObjectProfile/HierarchicalVisualizations#15] opened 2021-05-04 12:49 UTC
The user should be able to select a group of entity and

- move them together
- group them inside a container
- apply a layout (to be proposed) to only such entities
- 
It is acceptable that a group with entities of different nesting level cannot be relayouted.

**Comment by akevalion** [comment] 2021-08-12 03:35
duplicated issue

**Comment by NicolasAnquetil** [comment] 2021-09-07 15:10
ok closing because duplicate of #38

**Closed as completed by NicolasAnquetil** 2021-09-07 15:10 UTC
